apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx-app # <--some comments
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
      nodePort: 30913
