apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  namespace: devops-demo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx   # lowercase 'app'
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
